title       = "npm"
baseURL     = "https://npm-cli.tamnd.com/"
description = "A command line for npm."
contentDir  = "content"
outputDir   = "public"
theme       = "tago-doks"
syntaxHighlight = "true"

[params]
github = "https://github.com/tamnd/npm-cli"
